## Bining (Discretization)
Discretization means taking continuous numbers (like exact ages, prices, or temperatures) and grouping them into fixed buckets or categories.
Continuous data (Exact numbers): Age = 12, 18, 25, 42, 67, 80

Discretized/Binned data (Categories):

Bucket 1 (0–17): "Child"

Bucket 2 (18–59): "Adult"

Bucket 3 (60+): "Senior"

Instead of tracking every single decimal or exact number, you just assign each value to its corresponding "bin."

# The Reason we use it
1. To Handle Outliers
Extreme, unusual numbers (outliers) can pull a model off track.

Example: If most people in a dataset earn $30,000 to $80,000, but one person earns $10,000,000, that $10,000,000 is an outlier.

How binning helps: If you group incomes into high-level categories like Low, Medium, and High, that $10,000,000 simply falls into the High bin along with $150,000. The extreme value loses its power to distort your model's calculations.

2. To Improve the Value Spread
Sometimes raw data is skewed, chaotic, or spread unevenly, making it hard for machine learning algorithms (especially linear models or tree-based algorithms) to find clean patterns.

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import KBinsDiscretizer

In [2]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [3]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [6]:
df.isnull().sum()

Survived    0
Age         0
Fare        0
dtype: int64

In [5]:
df.dropna(inplace=True)

In [8]:
df.shape

(714, 3)

In [18]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [20]:
X_train

      Age      Fare
328  31.0   20.5250
73   26.0   14.4542
253  30.0   16.1000
719  33.0    7.7750
666  25.0   13.0000
..    ...       ...
92   46.0   61.1750
134  25.0   13.0000
337  41.0  134.5000
548  33.0   20.5250
130  33.0    7.8958

[571 rows x 2 columns]

In [22]:
clf = DecisionTreeClassifier()

In [24]:
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [25]:
accuracy_score(y_test,y_pred)

0.6363636363636364