In [3]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [7]:
df=pd.read_csv(r'D:\Programs\portfolio\MachineLearning\DataSets\titanic_toy.csv')

In [9]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [12]:
df.shape

(891, 4)

In [13]:
df.isnull().mean()

Age         0.198653
Fare        0.050505
Family      0.000000
Survived    0.000000
dtype: float64

In [15]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [29]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
Age_mean = x_train['Age'].mean()
Age_median = x_train['Age'].median()
Fare_mean = x_train['Fare'].mean()
Fare_median= x_train['Fare'].median()

In [36]:
x_train['Age_mean'] = x_train['Age'].fillna(Age_mean)
x_train['Age_median']= x_train['Age'].fillna(Age_median)

x_train['Fare_mean'] = x_train['Fare'].fillna(Fare_mean)
x_train['Fare_median'] = x_train['Fare'].fillna(Fare_median)

In [37]:
x_train.head()

      Age     Fare  Family  Age_mean  Age_median  Fare_mean  Fare_median
331  45.5  28.5000       0      45.5        45.5    28.5000      28.5000
733  23.0  13.0000       0      23.0        23.0    13.0000      13.0000
382  32.0   7.9250       0      32.0        32.0     7.9250       7.9250
704  26.0   7.8542       1      26.0        26.0     7.8542       7.8542
813   6.0  31.2750       6       6.0         6.0    31.2750      31.2750

In [35]:
x_train.isnull().mean()

Age            0.196629
Fare           0.050562
Family         0.000000
Age_mean       0.000000
Age_median     0.000000
Fare_mean      0.000000
Fare_median    0.000000
dtype: float64