In [21]:
import pandas as pd

In [22]:
df = pd.read_json("train.json")

# Seven(7) Question should we aske about our DAta

# 1) How big is the data

In [8]:
df.shape

(39774, 3)

# 2) How does the data look like?

In [12]:
df.head()
 # it will show the fisrt 5 rows

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [13]:
# if we want to show random rows then we can use sample function as
df.sample()

          id      cuisine                                        ingredients
27959  49198  southern_us  [olive oil, old bay seasoning, cream cheese, c...

# 3) what is the data type of columns

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39774 entries, 0 to 39773
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           39774 non-null  int64
 1   cuisine      39774 non-null  object
 2   ingredients  39774 non-null  object
dtypes: int64(1), object(2)
memory usage: 932.3+ KB

# 4) Are there any mising values

In [17]:
df.isnull().sum()

id             0
cuisine        0
ingredients    0
dtype: int64

# 5) How does the data look mathematically

In [19]:
df.describe()

                 id
count  39774.000000
mean   24849.536959
std    14360.035505
min        0.000000
25%    12398.250000
50%    24887.000000
75%    37328.500000
max    49717.000000

# 7) What is the corelation between the columns

In [27]:
df.corr()

ValueError: could not convert string to float: 'greek'