In [10]:
import pandas as pd

In [11]:
df = pd.read_json("train.json")
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

# **Dealing with SQL Data**

In [4]:
import mysql.connector

In [11]:
conn=mysql.connector.connect(host='localhost',user='root',password='Zk5622884',database='world')

In [18]:
pd.read_sql_query("SELECT * FROM CITY where countrycode like 'IND'",conn)
# conn = connection object which define the connection with MYSQL

C:\Users\BKlaptop\AppData\Local\Temp\ipykernel_14904\1845535399.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM CITY where countrycode like 'IND'",conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [ ]:
df=pd.read_json('https://jsonplaceholder.typicode.com/posts')
df=df.drop(columns=('userId'))
df

AttributeError: 'DataFrame' object has no attribute 'limit'

In [9]:
df.head(5)

,id,title,body
0,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...