In [4]:
import pandas as pd
import numpy as np

In [31]:
url = "https://raw.githubusercontent.com/fivethirtyeight/uber-tlc-foil-response/master/uber-trip-data/uber-raw-data-apr14.csv"

In [6]:
df = pd.read_csv(url , nrows=2000)

In [7]:
df.head()

          Date/Time      Lat      Lon    Base
0  4/1/2014 0:11:00  40.7690 -73.9549  B02512
1  4/1/2014 0:17:00  40.7267 -74.0345  B02512
2  4/1/2014 0:21:00  40.7316 -73.9873  B02512
3  4/1/2014 0:28:00  40.7588 -73.9776  B02512
4  4/1/2014 0:33:00  40.7594 -73.9722  B02512

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date/Time  2000 non-null   datetime64[ns]
 1   Lat        2000 non-null   float64
 2   Lon        2000 non-null   float64
 3   Base       2000 non-null   object
 4   date       2000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(2), object(1)
memory usage: 78.3+ KB

In [ ]:
# coverting into datetime
df['Date/Time'] = pd.to_datetime(df['Date/Time'])

# Extracting Time

In [21]:
df['time'] = df['Date/Time'].dt.time
df.sample(5)

,Date/Time,Lat,Lon,Base,date,time
460,2014-04-01 14:16:00,40.7595,-73.9736,B02512,2014-04-01 14:16:00,14:16:00
295,2014-04-01 11:03:00,40.7863,-73.9774,B02512,2014-04-01 11:03:00,11:03:00
1332,2014-04-02 10:03:00,40.7071,-74.0048,B02512,2014-04-02 10:03:00,10:03:00
1994,2014-04-02 18:20:00,40.7157,-74.0096,B02512,2014-04-02 18:20:00,18:20:00
1014,2014-04-02 00:11:00,40.6550,-73.9786,B02512,2014-04-02 00:11:00,00:11:00

# Extract Day

In [23]:
df['day'] = df['Date/Time'].dt.day_name()
df.sample(5)

,Date/Time,Lat,Lon,Base,date,time,day
781,2014-04-01 18:57:00,40.7584,-73.9724,B02512,2014-04-01 18:57:00,18:57:00,Tuesday
802,2014-04-01 19:13:00,40.7843,-73.9539,B02512,2014-04-01 19:13:00,19:13:00,Tuesday
434,2014-04-01 13:49:00,40.7685,-73.8624,B02512,2014-04-01 13:49:00,13:49:00,Tuesday
1648,2014-04-02 15:18:00,40.7521,-73.9855,B02512,2014-04-02 15:18:00,15:18:00,Wednesday
134,2014-04-01 07:29:00,40.7298,-73.9988,B02512,2014-04-01 07:29:00,07:29:00,Tuesday

# Extract Month

In [24]:
df['Month'] = df['Date/Time'].dt.month_name()
df.sample(5)

,Date/Time,Lat,Lon,Base,date,time,day,Month
347,2014-04-01 12:07:00,40.6864,-73.9747,B02512,2014-04-01 12:07:00,12:07:00,Tuesday,April
1009,2014-04-01 23:49:00,40.7661,-73.9693,B02512,2014-04-01 23:49:00,23:49:00,Tuesday,April
1968,2014-04-02 18:02:00,40.7255,-74.0358,B02512,2014-04-02 18:02:00,18:02:00,Wednesday,April
597,2014-04-01 16:30:00,40.7632,-73.9830,B02512,2014-04-01 16:30:00,16:30:00,Tuesday,April
83,2014-04-01 06:40:00,40.7858,-73.9546,B02512,2014-04-01 06:40:00,06:40:00,Tuesday,April

# Extract Year

In [26]:
df['year'] = df['Date/Time'].dt.year
df.sample(20)

,Date/Time,Lat,Lon,Base,date,time,day,Month,year
265,2014-04-01 10:32:00,40.6949,-74.1781,B02512,2014-04-01 10:32:00,10:32:00,Tuesday,April,2014
1889,2014-04-02 17:23:00,40.7195,-74.0042,B02512,2014-04-02 17:23:00,17:23:00,Wednesday,April,2014
361,2014-04-01 12:24:00,40.7732,-73.8857,B02512,2014-04-01 12:24:00,12:24:00,Tuesday,April,2014
472,2014-04-01 14:27:00,40.7275,-74.0010,B02512,2014-04-01 14:27:00,14:27:00,Tuesday,April,2014
401,2014-04-01 13:08:00,40.7458,-73.9870,B02512,2014-04-01 13:08:00,13:08:00,Tuesday,April,2014
143,2014-04-01 07:38:00,40.7752,-73.9637,B02512,2014-04-01 07:38:00,07:38:00,Tuesday,April,2014
660,2014-04-01 17:15:00,40.7199,-74.0043,B02512,2014-04-01 17:15:00,17:15:00,Tuesday,April,2014
1806,2014-04-02 16:43:00,40.7512,-73.9905,B02512,2014-04-02 16:43:00,16:43:00,Wednesday,April,2014
821,2014-04-01 19:29:00,40.7625,-73.9769,B02512,2014-04-01 19:29:00,19:29:00,Tuesday,April,2014
808,2014-04-01 19:15:00,40.7641,-73.9813,B02512,2014-04-01 19:15:00,19:15:00,Tuesday,April,2014
1507,2014-04-02 13:26:00,40.7209,-73.9949,B02512,2014-04-02 13:26:00,13:26:00,Wednesday,April,2014
1607,2014-04-02 14:51:00,40.8100,-73.9513,B02512,2014-04-02 14:51:00,14:51:00,Wednesday,April,2014
1847,2014-04-02 17:05:00,40.7514,-73.9777,B02512,2014-04-02 17:05:00,17:05:00,Wednesday,April,2014
1106,2014-04-02 06:41:00,40.7738,-73.9801,B02512,2014-04-02 06:41:00,06:41:00,Wednesday,April,2014
1664,2014-04-02 15:27:00,40.7468,-73.9981,B02512,2014-04-02 15:27:00,15:27:00,Wednesday,April,2014
1269,2014-04-02 08:52:00,40.7412,-74.0034,B02512,2014-04-02 08:52:00,08:52:00,Wednesday,April,2014
1862,2014-04-02 17:13:00,40.7557,-73.9832,B02512,2014-04-02 17:13:00,17:13:00,Wednesday,April,2014
373,2014-04-01 12:33:00,40.7031,-73.9853,B02512,2014-04-01 12:33:00,12:33:00,Tuesday,April,2014
66,2014-04-01 06:17:00,40.7651,-74.0820,B02512,2014-04-01 06:17:00,06:17:00,Tuesday,April,2014
521,2014-04-01 15:24:00,40.8247,-73.9735,B02512,2014-04-01 15:24:00,15:24:00,Tuesday,April,2014

In [30]:
df['Is_weakend'] = np.where(df['day'].isin(['Sunday' , 'Saturday']),1,0)
df.sample(5)

,Date/Time,Lat,Lon,Base,date,time,day,Month,year,Is_weakend
862,2014-04-01 20:06:00,40.7685,-73.8626,B02512,2014-04-01 20:06:00,20:06:00,Tuesday,April,2014,0
1791,2014-04-02 16:32:00,40.7529,-73.9701,B02512,2014-04-02 16:32:00,16:32:00,Wednesday,April,2014,0
1757,2014-04-02 16:18:00,40.8051,-73.9661,B02512,2014-04-02 16:18:00,16:18:00,Wednesday,April,2014,0
1008,2014-04-01 23:45:00,40.7231,-73.9987,B02512,2014-04-01 23:45:00,23:45:00,Tuesday,April,2014,0
1858,2014-04-02 17:11:00,40.7538,-73.9857,B02512,2014-04-02 17:11:00,17:11:00,Wednesday,April,2014,0

In [32]:
import datetime

In [44]:
Today = datetime.datetime.today()
Today

datetime.datetime(2026, 7, 27, 23, 2, 22, 975744)

In [49]:
(Today - df['Date/Time']).dt.days

0       4500
1       4500
2       4500
3       4500
4       4500
        ...
1995    4499
1996    4499
1997    4499
1998    4499
1999    4499
Name: Date/Time, Length: 2000, dtype: int64

# Working With Time

In [55]:
df['Hours'] = df['Date/Time'].dt.hour
df['Minutes'] = df['Date/Time'].dt.minute
df['secands'] = df['Date/Time'].dt.second

df.sample(5)

,Date/Time,Lat,Lon,Base,date,time,day,Month,year,Is_weakend,Hours,Minutes,secands
136,2014-04-01 07:30:00,40.7208,-73.9940,B02512,2014-04-01 07:30:00,07:30:00,Tuesday,April,2014,0,7,30,0
347,2014-04-01 12:07:00,40.6864,-73.9747,B02512,2014-04-01 12:07:00,12:07:00,Tuesday,April,2014,0,12,7,0
1171,2014-04-02 07:37:00,40.7951,-73.9761,B02512,2014-04-02 07:37:00,07:37:00,Wednesday,April,2014,0,7,37,0
890,2014-04-01 20:49:00,40.7138,-74.0635,B02512,2014-04-01 20:49:00,20:49:00,Tuesday,April,2014,0,20,49,0
603,2014-04-01 16:33:00,40.7106,-73.9858,B02512,2014-04-01 16:33:00,16:33:00,Tuesday,April,2014,0,16,33,0